name: Terraform Deploy
 
on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"
 
jobs:
  terraform:
    name: Plan & Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
 
    env:
      TF_VAR_render_api_key: ${{ secrets.RENDER_API_KEY }}
      TF_VAR_render_owner_id: ${{ secrets.RENDER_OWNER_ID }}
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~> 1.3"
 
      - name: Terraform Init
        run: terraform init
 
      - name: Terraform Format Check
        run: terraform fmt -check -recursive
 
      - name: Terraform Validate
        run: terraform validate
 
      - name: Terraform Plan
        run: terraform plan -out=tfplan
 
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan